// Runs after `vite build`: writes dist/config.js, which points the app and the interview page at the backend.
//   HIRERIZZ_API_URL = https://<your-backend>.onrender.com   (Vercel -> Project -> Settings -> Environment Variables)
// Unset = the pages call the address they were loaded from (local: `screening serve` serves everything).
import { existsSync, writeFileSync } from "node:fs";

const api = (process.env.HIRERIZZ_API_URL || "").trim().replace(/\/+$/, "");
if (!api) {
  console.warn("WARNING: HIRERIZZ_API_URL is not set; the pages will call their own address for the API.");
} else if (!/^https:\/\//.test(api)) {
  throw new Error(`HIRERIZZ_API_URL must start with https:// (got ${api})`);
}
if (!existsSync("dist/index.html") || !existsSync("dist/interview.html")) {
  throw new Error("dist/ is incomplete: run `vite build` first (npm run build does both)");
}
writeFileSync("dist/config.js", `// generated by build.mjs\nwindow.HIRERIZZ_API = ${JSON.stringify(api)};\n`);
console.log(`Built dist/ -> API ${api || "(same origin)"}`);
