// Vercel build: copy the static pages to dist/ and point them at the backend.
//   HIRERIZZ_API_URL = https://<your-backend>.onrender.com   (set in Vercel -> Project -> Settings -> Environment Variables)
import { copyFileSync, mkdirSync, writeFileSync } from "node:fs";

const api = (process.env.HIRERIZZ_API_URL || "").trim().replace(/\/+$/, "");
if (!api) {
  console.warn("WARNING: HIRERIZZ_API_URL is not set; the pages will call their own address for the API.");
} else if (!/^https:\/\//.test(api)) {
  throw new Error(`HIRERIZZ_API_URL must start with https:// (got ${api})`);
}
mkdirSync("dist", { recursive: true });
for (const f of ["index.html", "interview.html"]) copyFileSync(f, `dist/${f}`);
writeFileSync("dist/config.js", `// generated by build.mjs\nwindow.HIRERIZZ_API = ${JSON.stringify(api)};\n`);
console.log(`Built dist/ -> API ${api || "(same origin)"}`);
