// Address of the HireRizz backend API.
// Empty = the same address this page was loaded from (local: `screening serve` serves both).
// On Vercel this file is regenerated by build.mjs from the HIRERIZZ_API_URL environment variable.
window.HIRERIZZ_API = "";
